spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jlm?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password:

  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/, classpath:/public/

  #redis配置
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 50
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 5


server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8080
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#邮箱配置
email:
  username: 1427392461@qq.com
  password: grawlheposnuggcf

#配置外部访问文件
cbs:
  Path: file:/E:/software3-3-1/jlmfile/
  imagesPath: file:/E:/software3-3-1/jlmfile/uploadImg/
  ckImgPath: file:/E:/software3-3-1/jlmfile/ckupload/
